framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null
        cookie_lifetime: 86400  # 1 day
        gc_maxlifetime: 86400   # 1 day
    php_errors:
        log: true
    cache:
        app: cache.adapter.filesystem
    serializer:
        enabled: true
    messenger:
        enabled: false
    profiler:
        collect: true
        only_exceptions: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@dev:
    framework:
        profiler:
            collect: true