security:
  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\FormLoginAuthenticator
      logout:
        path: app_logout
        target: product_index
      remember_me:
        secret: '%kernel.secret%'
        lifetime: 604800 # 1 week
        path: /

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/cart, roles: PUBLIC_ACCESS }
    - { path: ^/coupon/apply, roles: PUBLIC_ACCESS }
    - { path: ^/checkout, roles: ROLE_USER }
    - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/, roles: PUBLIC_ACCESS }

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
