# config/routes.yaml
home:
    path: /
    controller: App\Controller\HomeController::index
product_index:
    path: /products
    controller: App\Controller\ProductController::index
product_index_category:
    path: /products/{category}
    controller: App\Controller\ProductController::index
    defaults: { category: null }
product_show:
    path: /products/{id}
    controller: App\Controller\ProductController::show
    requirements: { id: '\d+' }